### ISSUE TITLE
Adapt to use playframework/playframework#8827 

### ISSUE THREAD

**Issue by octonato** [playframework/play-java-forms-example#41]
@ignasi35, PR #39 was passing and therefore I merged it. 

Based on your comment [here](https://github.com/playframework/play-java-forms-example/pull/39#issuecomment-442889172), it seems that we need to change this template when we move to RC8. This issues is here to track it.

**Comment by ignasi35** [comment]
I posted the comment on the wrong sample (too many samples, too little time). This issue can be closed.

**Comment by ignasi35** [comment]
The correct comment is https://github.com/playframework/play-java-ebean-example/pull/82#issuecomment-442983513
